version: '3.8'
services:
  web:
    build: .
    container_name : celery-test-web
    ports:
      - 8001:8000
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - CELERY_RESULT_BACKEND=redis://redis:6379
    volumes:
      - ./data:/app/data
      - .:/app
  # 기본 큐 처리 워커
  # worker-default:
  #   build: .
  #   container_name: celery-worker-default
  #   command: celery -A background.celery.celery_app worker -Q celery --loglevel=info --concurrency=2
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #     redis:
  #       condition: service_started
  #   environment:
  #     - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
  #     - CELERY_RESULT_BACKEND=redis://redis:6379
  #   volumes:
  #     - ./data:/app/data
  #     - .:/app

  # 고우선순위 작업 처리 워커
  # worker-priority:
  #   build: .
  #   container_name: celery-worker-priority
  #   command: celery -A background.celery.celery_app worker -Q high-priority --loglevel=info --concurrency=1
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #     redis:
  #       condition: service_started
  #   environment:
  #     - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
  #     - CELERY_RESULT_BACKEND=redis://redis:6379
  #   volumes:
  #     - ./data:/app/data
  #     - .:/app

  worker:
    build: .
    container_name: celery-worker-default
    command: celery -A background.celery.celery_app worker --loglevel=info --concurrency=2
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - CELERY_RESULT_BACKEND=redis://redis:6379
    volumes:
      - ./data:/app/data
      - .:/app


  # FAISS/AI 작업 전용 워커 (예시)
  worker-ai:
    build: .
    container_name: celery-worker-ai
    command: celery -A background.celery.celery_app worker -Q ai-tasks,faiss-index --loglevel=info --concurrency=1
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - CELERY_RESULT_BACKEND=redis://redis:6379
    volumes:
      - ./data:/app/data
      - .:/app
      
  flower:
    build: .
    container_name: celery-test-flower
    command: celery -A background.celery.celery_app flower --port=5555
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - CELERY_RESULT_BACKEND=redis://redis:6379
    ports:
      - "5555:5555"
    volumes:
      - .:/app
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - "6379:6379" 
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: celery-test-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    ports: 
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  rabbitmq_data:
